### ISSUE TITLE
Add support for Regex based subscription.

### ISSUE THREAD

**Issue by rishisharmamt** [fluent/fluent-plugin-kafka#258] opened 2019-05-13 05:49 UTC
Fluentd input plugin should support regex topics so that logs from multiple topics can be collected.
For example, we are using kafka as a intermediate log storage from where logs are written to multiple endpoints - S3 (For archiving), Files on EBS backed volume (For tailing and Searching). Each application writes logs into it's own topic. To collect logs from all applications,  topics  of all applications must be kept as configuration and must be updated when new applications are developed. Having a regex of all application topics is easier to implement then udpating log configuration to enable log collection for an application.

**Comment by gabe-sorensen** [comment] 2019-08-23 18:59
Is this a duplicate of #147?

**Comment by cosmo0920** [comment] 2020-11-24 05:35
It seems that ruby-kafka already supports regex topic subscription:
https://github.com/zendesk/ruby-kafka/pull/700

Does anyone want to introduce regex type of subscription?

**Comment by repeatedly** [comment] 2020-11-26 17:52
This issue has been fixed via https://github.com/fluent/fluent-plugin-kafka/pull/335

**Closed by repeatedly** 2020-11-26 17:52 UTC
